pages:
  stage: deploy
  script:
    - mkdir public
    - cp index.html public/
    - cp -r css public/
    - cp -r js public/
    - cp README.md public/
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "main"
